---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/rentals":
    get:
      summary: list rentals
      tags:
      - Rentals
      security:
      - bearerAuth: []
      parameters:
      - name: token
      responses:
        '200':
          description: successful
    post:
      summary: create rental
      responses:
        '200':
          description: successful
  "/api/v1/rentals/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update rental
      responses:
        '200':
          description: successful
    put:
      summary: update rental
      responses:
        '200':
          description: successful
    delete:
      summary: delete rental
      responses:
        '200':
          description: successful
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: localhost:3001
securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearer_format: JWT
